### ISSUE TITLE
M2 Max (MacBook Pro 16) & A16 Bionic (iPhone 14 Pro Max)

### ISSUE THREAD

**Issue by jtgil** [mr-mobster/AppleSiliconPowerTest#10]
Great that there are people still using the forums for useful stuff!

Here are some results for the M2 Max on a MBP 16.
[m2_max_results.zip](https://github.com/mr-mobster/AppleSiliconPowerTest/files/12736675/m2_max_results.zip)

Here are some results for the A16 in the iPhone 14PM.
[a16_results.zip](https://github.com/mr-mobster/AppleSiliconPowerTest/files/12736667/a16_results.zip)

Thanks for the work and looking forward for more informative graphics!

**Comment by mr-mobster** [comment]
Thank you, much appreciated!
